export const mockApartments = [
  {
    apartmentID: 1,
    code: "Unit 101, Tower A",
    building: "Tower A",
    floor: 1,
    area: 1200,
    status: "occupied",
    residents: ["Alice Wonderland", "Bob The Builder"],
  },
  {
    apartmentID: 2,
    code: "Unit 102, Tower A",
    building: "Tower A",
    floor: 1,
    area: 1500,
    status: "vacant",
    residents: [],
  },
  {
    apartmentID: 3,
    code: "Penthouse 1, Tower B",
    building: "Tower B",
    floor: 20,
    area: 3500,
    status: "occupied",
    residents: ["Charles Xavier"],
  },
  {
    apartmentID: 4,
    code: "Unit 205, Tower A",
    building: "Tower A",
    floor: 2,
    area: 800,
    status: "maintenance",
    residents: [],
  },
  {
    apartmentID: 5,
    code: "Unit 303, Tower C",
    building: "Tower C",
    floor: 3,
    area: 1250,
    status: "occupied",
    residents: ["Diana Prince"],
  },
];

export const mockRoles = [
  {
    roleID: 1,
    name: "Management_Head",
    description: "Trưởng ban quản lý",
  },
  {
    roleID: 2,
    name: "Management_Vice",
    description: "Phó ban quản lý",
  },
  {
    roleID: 3,
    name: "Team_Leader",
    description: "Tổ trưởng",
  },
  {
    roleID: 4,
    name: "Team_Vice_Leader",
    description: "Tổ phó",
  },
  {
    roleID: 5,
    name: "Staff",
    description: "Nhân viên thuộc ban quản lý",
  },
  {
    roleID: 6,
    name: "Resident",
    description: "Cư dân sinh sống tại chung cư",
  },
];

export const mockResidents = [
  {
    residentID: 1,
    fullName: "Nguyễn Thị Mai",
    birthDate: "1990-04-12",
    gender: "Female",
    idNumber: "987654321",
    phone: "0901234567",
    email: "mainguyen@example.com",
    roleID: 6,
    residentAccountID: 1,
    role: {
      roleID: 6,
      name: "Resident",
      description: "Cư dân sinh sống tại chung cư",
    },
  },
  {
    residentID: 2,
    fullName: "Trần Văn B",
    birthDate: "1985-06-20",
    gender: "Male",
    idNumber: "876543219",
    phone: "0902345678",
    email: "tranvb@example.com",
    roleID: 6,
    residentAccountID: 2,
    role: {
      roleID: 6,
      name: "Resident",
      description: "Cư dân sinh sống tại chung cư",
    },
  },
  {
    residentID: 3,
    fullName: "Lê Thị C",
    birthDate: "1992-09-10",
    gender: "Female",
    idNumber: "765432198",
    phone: "0903456789",
    email: "lethic@example.com",
    roleID: 6,
    residentAccountID: 3,
    role: {
      roleID: 6,
      name: "Resident",
      description: "Cư dân sinh sống tại chung cư",
    },
  },
  {
    residentID: 4,
    fullName: "Phạm Duy Dũng",
    birthDate: "1988-12-01",
    gender: "Male",
    idNumber: "654321987",
    phone: "0904567890",
    email: "duydung@example.com",
    roleID: 6,
    residentAccountID: 4,
    role: {
      roleID: 6,
      name: "Resident",
      description: "Cư dân sinh sống tại chung cư",
    },
  },
  {
    residentID: 5,
    fullName: "Đỗ Mỹ Linh",
    birthDate: "1995-11-25",
    gender: "Female",
    idNumber: "543219876",
    phone: "0905678901",
    email: "mylinh@example.com",
    roleID: 6,
    residentAccountID: 5,
    role: {
      roleID: 6,
      name: "Resident",
      description: "Cư dân sinh sống tại chung cư",
    },
  },
];

export const mockDepartments = [
  {
    departmentID: 1,
    name: "Management Department",
    description: "Bộ phận quản lý, bao gồm trưởng ban và phó ban quản lý",
  },
  {
    departmentID: 2,
    name: "Technical Department",
    description: "Phụ trách các vấn đề kỹ thuật của tòa nhà",
  },
  {
    departmentID: 3,
    name: "IT Department",
    description: "Quản lý hệ thống công nghệ thông tin",
  },
  {
    departmentID: 4,
    name: "Administration Department",
    description: "Xử lý công việc hành chính và nhân sự",
  },
  {
    departmentID: 5,
    name: "Finance Department",
    description: "Quản lý tài chính và kế toán",
  },
  {
    departmentID: 6,
    name: "Security Department",
    description: "Đảm bảo an ninh cho toàn bộ khu vực",
  },
  {
    departmentID: 7,
    name: "Cleaning Department",
    description: "Chịu trách nhiệm dọn dẹp và vệ sinh khu vực",
  },
  {
    departmentID: 8,
    name: "Customer Service Department",
    description: "Giải đáp và xử lý yêu cầu từ cư dân",
  },
];

export const mockEmployees = [
  {
    employeeID: 1,
    fullName: "Trần Văn Minh",
    birthDate: "1985-06-15",
    gender: "Male",
    idNumber: "123456789",
    phone: "0123456789",
    email: "tranvanminh@email.com",
    startDate: "2020-01-01",
    endDate: null,
    employeeAccountID: 1,
    roleID: 1,
    departmentID: 1,
    role: {
      roleID: 1,
      name: "Manager",
      description: "Department manager",
    },
    department: {
      departmentID: 1,
      name: "Quản lý",
      description: "Phòng quản lý chung",
    },
  },
  {
    employeeID: 2,
    fullName: "Nguyễn Thị Hương",
    birthDate: "1990-03-20",
    gender: "Female",
    idNumber: "987654321",
    phone: "0987654321",
    email: "nguyenthiuong@email.com",
    startDate: "2021-02-15",
    endDate: null,
    employeeAccountID: 2,
    roleID: 2,
    departmentID: 2,
    role: {
      roleID: 2,
      name: "Technician",
      description: "Maintenance technician",
    },
    department: {
      departmentID: 2,
      name: "Bảo trì",
      description: "Phòng bảo trì và sửa chữa",
    },
  },
  {
    employeeID: 3,
    fullName: "Lê Văn Tú",
    birthDate: "1988-11-10",
    gender: "Male",
    idNumber: "456789123",
    phone: "0456789123",
    email: "levantu@email.com",
    startDate: "2019-05-01",
    endDate: null,
    employeeAccountID: 3,
    roleID: 3,
    departmentID: 3,
    role: {
      roleID: 3,
      name: "Security",
      description: "Security officer",
    },
    department: {
      departmentID: 3,
      name: "An ninh",
      description: "Phòng an ninh và bảo vệ",
    },
  },
  {
    employeeID: 4,
    fullName: "Phạm Thị Lan",
    birthDate: "1992-07-25",
    gender: "Female",
    idNumber: "789123456",
    phone: "0789123456",
    email: "phamthilan@email.com",
    startDate: "2022-01-10",
    endDate: null,
    employeeAccountID: 4,
    roleID: 4,
    departmentID: 4,
    role: {
      roleID: 4,
      name: "Service",
      description: "Service staff",
    },
    department: {
      departmentID: 4,
      name: "Dịch vụ",
      description: "Phòng dịch vụ cư dân",
    },
  },
  {
    employeeID: 5,
    fullName: "Hoàng Văn Sơn",
    birthDate: "1987-09-18",
    gender: "Male",
    idNumber: "321654987",
    phone: "0321654987",
    email: "hoangvanson@email.com",
    startDate: "2020-08-01",
    endDate: null,
    employeeAccountID: 5,
    roleID: 2,
    departmentID: 2,
    role: {
      roleID: 2,
      name: "Technician",
      description: "Maintenance technician",
    },
    department: {
      departmentID: 2,
      name: "Bảo trì",
      description: "Phòng bảo trì và sửa chữa",
    },
  },
];

export const mockPermissions = [
  {
    permissionID: 1,
    permissionCode: "USER_MANAGE",
    permissionDes: "Quản lý người dùng",
  },
  {
    permissionID: 2,
    permissionCode: "RESIDENT_MANAGE",
    permissionDes: "Quản lý cư dân",
  },
  {
    permissionID: 3,
    permissionCode: "APARTMENT_MANAGE",
    permissionDes: "Quản lý căn hộ",
  },
  {
    permissionID: 4,
    permissionCode: "SERVICE_MANAGE",
    permissionDes: "Quản lý dịch vụ",
  },
  {
    permissionID: 5,
    permissionCode: "VEHICLE_MANAGE",
    permissionDes: "Quản lý phương tiện",
  },
  {
    permissionID: 6,
    permissionCode: "TASK_MANAGE",
    permissionDes: "Quản lý công việc",
  },
  {
    permissionID: 7,
    permissionCode: "EMPLOYEE_MANAGE",
    permissionDes: "Quản lý nhân viên",
  },
  {
    permissionID: 8,
    permissionCode: "MAINTENANCE_MANAGE",
    permissionDes: "Quản lý bảo trì/sửa chữa",
  },
  {
    permissionID: 9,
    permissionCode: "COMPLAINT_MANAGE",
    permissionDes: "Quản lý phản ánh",
  },
  {
    permissionID: 10,
    permissionCode: "FEE_MANAGE",
    permissionDes: "Quản lý phí",
  },
  {
    permissionID: 11,
    permissionCode: "BILL_MANAGE",
    permissionDes: "Quản lý hoá đơn",
  },
  {
    permissionID: 12,
    permissionCode: "REPORT_VIEW",
    permissionDes: "Báo cáo thống kê",
  },
];

export const mockRoleDepartmentPermissions = [
  // Management Head permissions
  { roleID: 1, departmentID: 1, permissionID: 1 },
  { roleID: 1, departmentID: 1, permissionID: 2 },
  { roleID: 1, departmentID: 1, permissionID: 3 },
  { roleID: 1, departmentID: 1, permissionID: 4 },
  { roleID: 1, departmentID: 1, permissionID: 5 },
  { roleID: 1, departmentID: 1, permissionID: 6 },
  { roleID: 1, departmentID: 1, permissionID: 7 },
  { roleID: 1, departmentID: 1, permissionID: 8 },
  { roleID: 1, departmentID: 1, permissionID: 9 },
  { roleID: 1, departmentID: 1, permissionID: 10 },
  { roleID: 1, departmentID: 1, permissionID: 11 },
  { roleID: 1, departmentID: 1, permissionID: 12 },
  // Management Vice permissions
  { roleID: 2, departmentID: 1, permissionID: 1 },
  { roleID: 2, departmentID: 1, permissionID: 2 },
  { roleID: 2, departmentID: 1, permissionID: 3 },
  { roleID: 2, departmentID: 1, permissionID: 4 },
  { roleID: 2, departmentID: 1, permissionID: 5 },
  { roleID: 2, departmentID: 1, permissionID: 6 },
  { roleID: 2, departmentID: 1, permissionID: 7 },
  { roleID: 2, departmentID: 1, permissionID: 8 },
  { roleID: 2, departmentID: 1, permissionID: 9 },
  { roleID: 2, departmentID: 1, permissionID: 10 },
  { roleID: 2, departmentID: 1, permissionID: 11 },
  { roleID: 2, departmentID: 1, permissionID: 12 },
  // Team Leader permissions
  { roleID: 3, departmentID: 3, permissionID: 1 },
  { roleID: 3, departmentID: 3, permissionID: 6 },
  // Team Vice Leader permissions
  { roleID: 4, departmentID: 3, permissionID: 1 },
  { roleID: 4, departmentID: 3, permissionID: 6 },
  // Staff permissions
  { roleID: 5, departmentID: 3, permissionID: 1 },
];

export const mockUserRoles = [
  {
    roleID: 1,
    name: "Super Admin",
    description: "Quản trị viên cấp cao nhất",
    createdAt: "2024-01-01T00:00:00",
    updatedAt: "2024-01-01T00:00:00",
    isDeleted: false,
  },
  {
    roleID: 2,
    name: "Admin",
    description: "Quản trị viên",
    createdAt: "2024-01-01T00:00:00",
    updatedAt: "2024-01-01T00:00:00",
    isDeleted: false,
  },
  {
    roleID: 3,
    name: "Manager",
    description: "Quản lý",
    createdAt: "2024-01-01T00:00:00",
    updatedAt: "2024-01-01T00:00:00",
    isDeleted: false,
  },
  {
    roleID: 4,
    name: "Staff",
    description: "Nhân viên",
    createdAt: "2024-01-01T00:00:00",
    updatedAt: "2024-01-01T00:00:00",
    isDeleted: false,
  },
];

export const mockUsers = [
  {
    userID: 1,
    username: "admin1",
    password: "hashed_password_here",
    email: "vana@example.com",
    fullName: "Nguyễn Văn A",
    phone: "0912345678",
    status: "active",
    roleID: 1,
    departmentID: 1,
    lastLogin: "2024-03-15T08:30:00",
    createdAt: "2020-01-01T00:00:00",
    updatedAt: "2024-01-01T00:00:00",
    isDeleted: false,
    role: {
      roleID: 1,
      name: "Management_Head",
      description: "Trưởng ban quản lý",
    },
    department: {
      departmentID: 1,
      name: "Management Department",
      description: "Bộ phận quản lý, bao gồm trưởng ban và phó ban quản lý",
    },
  },
  {
    userID: 2,
    username: "viceadmin1",
    password: "hashed_password_here",
    email: "thingoc@example.com",
    fullName: "Trần Thị Ngọc",
    phone: "0922345678",
    status: "active",
    roleID: 2,
    departmentID: 1,
    lastLogin: "2024-03-14T15:45:00",
    createdAt: "2021-03-15T00:00:00",
    updatedAt: "2024-01-02T00:00:00",
    isDeleted: false,
    role: {
      roleID: 2,
      name: "Management_Vice",
      description: "Phó ban quản lý",
    },
    department: {
      departmentID: 1,
      name: "Management Department",
      description: "Bộ phận quản lý, bao gồm trưởng ban và phó ban quản lý",
    },
  },
  {
    userID: 3,
    username: "viceadmin2",
    password: "hashed_password_here",
    email: "tuanlm@example.com",
    fullName: "Lê Minh Tuấn",
    phone: "0932345678",
    status: "active",
    roleID: 2,
    departmentID: 1,
    lastLogin: "2024-03-13T10:20:00",
    createdAt: "2019-08-01T00:00:00",
    updatedAt: "2024-01-03T00:00:00",
    isDeleted: false,
    role: {
      roleID: 2,
      name: "Management_Vice",
      description: "Phó ban quản lý",
    },
    department: {
      departmentID: 1,
      name: "Management Department",
      description: "Bộ phận quản lý, bao gồm trưởng ban và phó ban quản lý",
    },
  },
  {
    userID: 4,
    username: "staff1",
    password: "hashed_password_here",
    email: "hanhpham@example.com",
    fullName: "Phạm Thị Hạnh",
    phone: "0942345678",
    status: "active",
    roleID: 5,
    departmentID: 2,
    lastLogin: "2024-03-12T14:15:00",
    createdAt: "2022-06-01T00:00:00",
    updatedAt: "2024-01-04T00:00:00",
    isDeleted: false,
    role: {
      roleID: 5,
      name: "Staff",
      description: "Nhân viên thuộc ban quản lý",
    },
    department: {
      departmentID: 2,
      name: "Technical Department",
      description: "Phụ trách các vấn đề kỹ thuật của tòa nhà",
    },
  },
  {
    userID: 5,
    username: "staff2",
    password: "hashed_password_here",
    email: "staff2@apartmaster.com",
    fullName: "Hoàng Văn Nhân Viên",
    phone: "0321654987",
    status: "inactive",
    roleID: 4,
    departmentID: 1,
    lastLogin: "2024-03-10T09:30:00",
    createdAt: "2024-01-05T00:00:00",
    updatedAt: "2024-01-05T00:00:00",
    isDeleted: false,
    role: {
      roleID: 4,
      name: "Staff",
      description: "Nhân viên",
    },
    department: {
      departmentID: 1,
      name: "Quản lý",
      description: "Phòng quản lý chung",
    },
  },
];

export const mockApartmentFees = [
  {
    feeID: 1,
    name: "Phí quản lý",
    description: "Phí quản lý chung cư hàng tháng",
    amount: 500000,
    type: "monthly",
    isActive: true,
  },
  {
    feeID: 2,
    name: "Phí gửi xe",
    description: "Phí gửi xe tháng",
    amount: 300000,
    type: "monthly",
    isActive: true,
  },
  {
    feeID: 3,
    name: "Phí bảo trì",
    description: "Phí bảo trì định kỳ",
    amount: 200000,
    type: "quarterly",
    isActive: true,
  },
];

export const mockServiceFees = [
  {
    serviceID: 1,
    name: "Dọn dẹp",
    description: "Dịch vụ dọn dẹp căn hộ",
    amount: 150000,
    type: "per_use",
    isActive: true,
  },
  {
    serviceID: 2,
    name: "Giặt ủi",
    description: "Dịch vụ giặt ủi",
    amount: 200000,
    type: "per_use",
    isActive: true,
  },
  {
    serviceID: 3,
    name: "Sửa chữa",
    description: "Dịch vụ sửa chữa",
    amount: 0,
    type: "per_use",
    isActive: true,
  },
];

export const mockBills = [
  {
    billID: 1,
    apartmentID: 1,
    residentID: 1,
    month: "2024-03",
    totalAmount: 950000,
    status: "paid",
    dueDate: "2024-03-15",
    paidDate: "2024-03-10",
    createdAt: "2024-03-01T00:00:00",
    updatedAt: "2024-03-10T00:00:00",
    isDeleted: false,
    details: [
      {
        detailID: 1,
        billID: 1,
        feeID: 1,
        amount: 500000,
        type: "apartment",
        description: "Phí quản lý tháng 3/2024",
      },
      {
        detailID: 2,
        billID: 1,
        feeID: 2,
        amount: 300000,
        type: "apartment",
        description: "Phí gửi xe tháng 3/2024",
      },
      {
        detailID: 3,
        billID: 1,
        serviceID: 1,
        amount: 150000,
        type: "service",
        description: "Dịch vụ dọn dẹp ngày 05/03/2024",
      },
    ],
    apartment: {
      apartmentID: 1,
      code: "Unit 101, Tower A",
      building: "Tower A",
      floor: 1,
      area: 1200,
      status: "occupied",
    },
    resident: {
      residentID: 1,
      fullName: "Nguyễn Thị Mai",
      phone: "0901234567",
      email: "mainguyen@example.com",
    },
  },
  {
    billID: 2,
    apartmentID: 2,
    residentID: 2,
    month: "2024-03",
    totalAmount: 800000,
    status: "pending",
    dueDate: "2024-03-15",
    paidDate: null,
    createdAt: "2024-03-01T00:00:00",
    updatedAt: "2024-03-01T00:00:00",
    isDeleted: false,
    details: [
      {
        detailID: 4,
        billID: 2,
        feeID: 1,
        amount: 500000,
        type: "apartment",
        description: "Phí quản lý tháng 3/2024",
      },
      {
        detailID: 5,
        billID: 2,
        feeID: 2,
        amount: 300000,
        type: "apartment",
        description: "Phí gửi xe tháng 3/2024",
      },
    ],
    apartment: {
      apartmentID: 2,
      code: "Unit 102, Tower A",
      building: "Tower A",
      floor: 1,
      area: 1500,
      status: "occupied",
    },
    resident: {
      residentID: 2,
      fullName: "Trần Văn B",
      phone: "0902345678",
      email: "tranvb@example.com",
    },
  },
  {
    billID: 3,
    apartmentID: 3,
    residentID: 3,
    month: "2024-03",
    totalAmount: 1150000,
    status: "overdue",
    dueDate: "2024-03-15",
    paidDate: null,
    createdAt: "2024-03-01T00:00:00",
    updatedAt: "2024-03-01T00:00:00",
    isDeleted: false,
    details: [
      {
        detailID: 6,
        billID: 3,
        feeID: 1,
        amount: 500000,
        type: "apartment",
        description: "Phí quản lý tháng 3/2024",
      },
      {
        detailID: 7,
        billID: 3,
        feeID: 2,
        amount: 300000,
        type: "apartment",
        description: "Phí gửi xe tháng 3/2024",
      },
      {
        detailID: 8,
        billID: 3,
        serviceID: 2,
        amount: 200000,
        type: "service",
        description: "Dịch vụ giặt ủi ngày 10/03/2024",
      },
      {
        detailID: 9,
        billID: 3,
        serviceID: 3,
        amount: 150000,
        type: "service",
        description: "Dịch vụ sửa chữa ngày 15/03/2024",
      },
    ],
    apartment: {
      apartmentID: 3,
      code: "Penthouse 1, Tower B",
      building: "Tower B",
      floor: 20,
      area: 3500,
      status: "occupied",
    },
    resident: {
      residentID: 3,
      fullName: "Lê Thị C",
      phone: "0903456789",
      email: "lethic@example.com",
    },
  },
];
